---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-extendeddeployment-io-v1beta1-extendeddeployment
  failurePolicy: Fail
  name: mextendeddeployment-v1beta1.kb.io
  rules:
  - apiGroups:
    - extendeddeployment.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - extendeddeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-extendeddeployment-io-v1beta1-inplaceset
  failurePolicy: Fail
  name: minplaceset-v1beta1.kb.io
  rules:
  - apiGroups:
    - extendeddeployment.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inplacesets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-extendeddeployment-io-v1beta1-extendeddeployment
  failurePolicy: Fail
  name: vextendeddeployment-v1beta1.kb.io
  rules:
  - apiGroups:
    - extendeddeployment.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - extendeddeployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-extendeddeployment-io-v1beta1-inplaceset
  failurePolicy: Fail
  name: vinplaceset-v1beta1.kb.io
  rules:
  - apiGroups:
    - extendeddeployment.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inplacesets
  sideEffects: None
