apiVersion: v1
kind: Service
metadata:
  name: extended-deployment-metrics
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: extended-deployment
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: metrics
      protocol: TCP
      port: 8443
      targetPort: 18443
