# permissions for end users to view deployregions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: extended-deployment
    app.kubernetes.io/managed-by: kustomize
  name: deployregion-viewer-role
rules:
- apiGroups:
  - extendeddeployment.io
  resources:
  - deployregions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extendeddeployment.io
  resources:
  - deployregions/status
  verbs:
  - get
