# permissions for end users to view inplacesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: extended-deployment
    app.kubernetes.io/managed-by: kustomize
  name: inplaceset-viewer-role
rules:
- apiGroups:
  - extendeddeployment.io
  resources:
  - inplacesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extendeddeployment.io
  resources:
  - inplacesets/status
  verbs:
  - get
