---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - extendeddeployment.io
  resources:
  - deployregions
  - extendeddeployments
  - inplacesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extendeddeployment.io
  resources:
  - deployregions/finalizers
  verbs:
  - update
- apiGroups:
  - extendeddeployment.io
  resources:
  - deployregions/status
  - extendeddeployments/status
  - inplacesets/status
  verbs:
  - get
  - patch
  - update
